# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nothing/Tetris/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),Tetris)

$(call add-radio-file-sha1-checked,radio/apusys.img,e73eb128f86c96cef5eaf5dc59639b64964f5f7f)
$(call add-radio-file-sha1-checked,radio/ccu.img,c349d071ee61127276acefd91cb591100b3d5b59)
$(call add-radio-file-sha1-checked,radio/connsys_bt.img,5ccc86567797e23e068e612311066037d3a1028f)
$(call add-radio-file-sha1-checked,radio/connsys_gnss.img,cf649cd025249521844919dfc02c75848dffb84a)
$(call add-radio-file-sha1-checked,radio/connsys_wifi.img,a59f82b19ecdee2811c766eb09eb96b44a9ef3fc)
$(call add-radio-file-sha1-checked,radio/dpm.img,03196e7b33b6a67f2abf80deb7ba954e0ad21b43)
$(call add-radio-file-sha1-checked,radio/gpueb.img,e9e0abed3f01697be642d8b3392aba6c3b1b1d49)
$(call add-radio-file-sha1-checked,radio/gz.img,1bd972302ac586279130f9a94ecd413cb93c952f)
$(call add-radio-file-sha1-checked,radio/lk.img,6e2c986e0c1d7374776fef6baa0517fd218fd43c)
$(call add-radio-file-sha1-checked,radio/logo.img,10bcfbc66189a2f8fa0440abd9e6d03cc05fae0c)
$(call add-radio-file-sha1-checked,radio/mcf_ota.img,3b684a39418c62d5eb77d458fd1092682a9e5075)
$(call add-radio-file-sha1-checked,radio/mcupm.img,2192bcfa6904c33f49f3a7160f0b5a4c8b30ac65)
$(call add-radio-file-sha1-checked,radio/modem.img,02f86c2dabdbef6a384912e3ab9d3f40353da441)
$(call add-radio-file-sha1-checked,radio/pi_img.img,b295b9e7d2d1123cb6be508888e8e58867533afd)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,148271cccb779d9727a7ff2bf9450c118e7a4024)
$(call add-radio-file-sha1-checked,radio/scp.img,5e57470c0c81115152f07ac6104587323ae5966e)
$(call add-radio-file-sha1-checked,radio/spmfw.img,2eebc6c16fbfc0fb06a3acc24a7b0181aa0a0b56)
$(call add-radio-file-sha1-checked,radio/sspm.img,8ba1d2eab0141119f73c745143684079018283bb)
$(call add-radio-file-sha1-checked,radio/tee.img,a8b8c9a18cbb5ba53ca72833e9eaaa4f650d29cf)
$(call add-radio-file-sha1-checked,radio/vcp.img,3c8fa3e2f9f6527e5045c525f7112f941230ec85)

endif
