# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nothing/Tetris/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),Tetris)

$(call add-radio-file-sha1-checked,radio/apusys.img,0bdedcae3f206e7f283f6ddd8c2e426f4188f8c6)
$(call add-radio-file-sha1-checked,radio/ccu.img,813a8dc1302773cedb83c0a3b270751153a2b2cf)
$(call add-radio-file-sha1-checked,radio/connsys_bt.img,74ee33d3a32b077e0eb9a12f8542f00bae851885)
$(call add-radio-file-sha1-checked,radio/connsys_gnss.img,23afd31d58a6b9385c6affa3c91c645aa7708489)
$(call add-radio-file-sha1-checked,radio/connsys_wifi.img,24c907bee7855996293c64e3babf79984df8867b)
$(call add-radio-file-sha1-checked,radio/dpm.img,02022203c7896671f7511a38c660522d730b6cf5)
$(call add-radio-file-sha1-checked,radio/gpueb.img,765de8497ab638d2c7d00bb53dd1eea2a68a9870)
$(call add-radio-file-sha1-checked,radio/gz.img,b32499078369bd8604a2e18d3e34c81b6a64df7c)
$(call add-radio-file-sha1-checked,radio/lk.img,f6dd1f634f86e107cfeb7c0b22d89e01dcac8a43)
$(call add-radio-file-sha1-checked,radio/logo.img,66a6e73a7ac9b34e5b760ad7b3557d35e6178e56)
$(call add-radio-file-sha1-checked,radio/mcf_ota.img,5a19a11cdcd12001a758ff7553de0dd777e50744)
$(call add-radio-file-sha1-checked,radio/mcupm.img,04b91e4f74cb897d4f00c8b5e69783c45bce5444)
$(call add-radio-file-sha1-checked,radio/modem.img,54191ebd661beb1db82ce83e94de122dd76476fc)
$(call add-radio-file-sha1-checked,radio/pi_img.img,4e641cf541edc812a2abcce9cb3317b5477513e5)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,9cbc60f975d7e2036a50dd67e12639c7e7f6304c)
$(call add-radio-file-sha1-checked,radio/scp.img,a5961658954d98cb488ff900ed84a954c46c6983)
$(call add-radio-file-sha1-checked,radio/spmfw.img,10c0c4d2015b6ec3ff297ae1a2720e14f96c0368)
$(call add-radio-file-sha1-checked,radio/sspm.img,b8de473f3741d55b23972ad6c2e7397ef18844be)
$(call add-radio-file-sha1-checked,radio/tee.img,0dd18799f471e8fdaa798fcc5658b7cf9b27f51c)
$(call add-radio-file-sha1-checked,radio/vcp.img,2fe43c56493ff5e56c5f1cb48fa3771096f920f2)

endif
