# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nothing/Tetris/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),Tetris)

$(call add-radio-file-sha1-checked,radio/apusys.img,c9e27763a98b7dc4d52005ae15e3b5c59b0976fb)
$(call add-radio-file-sha1-checked,radio/ccu.img,37fe83ed649d180167fdc814c9091f6bd4055987)
$(call add-radio-file-sha1-checked,radio/connsys_bt.img,43c3bd0158995b611f125016225e6f4cbf8de7ca)
$(call add-radio-file-sha1-checked,radio/connsys_gnss.img,cde791a5056524f7c897735446be212169471307)
$(call add-radio-file-sha1-checked,radio/connsys_wifi.img,1f0c10d85cf1846df96236d80db3ead8cdde5eaa)
$(call add-radio-file-sha1-checked,radio/dpm.img,aaf515d3e82fbd99fc80b5eac092eabb065adff4)
$(call add-radio-file-sha1-checked,radio/gpueb.img,3096b46bf088dd03250a94f14e5c00ef28f03266)
$(call add-radio-file-sha1-checked,radio/gz.img,b3125a3eab89ee4be7cbc6d5a46dac071fd0458a)
$(call add-radio-file-sha1-checked,radio/lk.img,700eaf8dcfac826bce755d540b08f83b347aad60)
$(call add-radio-file-sha1-checked,radio/logo.img,4ca20f462aede58dc8aafde1e48607e7d67ed7b4)
$(call add-radio-file-sha1-checked,radio/mcf_ota.img,3b48a3ccfe1db0a3d6c51b163e8c028c04930c3a)
$(call add-radio-file-sha1-checked,radio/mcupm.img,2eb8b8a52ad5cfbf973db192d7a8f6cc117c7f9a)
$(call add-radio-file-sha1-checked,radio/modem.img,4d01a4607f30f10a54f8bc4619c2ce9db56fae4a)
$(call add-radio-file-sha1-checked,radio/pi_img.img,08db1bc139a90853da23d67526eb366fec88c8dc)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,d6f98bdb5a1eecb61cdb8b4f5e09425131592652)
$(call add-radio-file-sha1-checked,radio/scp.img,a982aaa6dc6dc9b047c44d9bba45c588df616e6e)
$(call add-radio-file-sha1-checked,radio/spmfw.img,6958e3d72ff2074ca3047ea57558bb5e127d4afa)
$(call add-radio-file-sha1-checked,radio/sspm.img,3a26da9df1ebda9919822cd5b8ff17fecec80958)
$(call add-radio-file-sha1-checked,radio/tee.img,7f3581e9a29c7e945f169dad81ced03f6ef43fbf)
$(call add-radio-file-sha1-checked,radio/vcp.img,7038a41122f1afbaf96462e141832941d6b913f2)

endif
