# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nothing/Tetris/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    apusys \
    ccu \
    connsys_bt \
    connsys_gnss \
    connsys_wifi \
    dpm \
    gpueb \
    gz \
    lk \
    logo \
    mcf_ota \
    mcupm \
    modem \
    pi_img \
    preloader_raw \
    scp \
    spmfw \
    sspm \
    tee \
    vcp
